name: saasaki_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  provider: ^6.1.2
  country_picker: ^2.0.21
  pin_code_fields: ^8.0.1
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.13.1
  flutter_slidable: ^3.0.1
  flutter_datetime_picker_plus: ^2.1.0
  firebase_app_check: ^0.2.1+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/images/
