// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmRFSWTUM6tmVAegbDyv6u_zlwvmGM28',
    appId: '1:81377161795:web:6b5ab809017cf28d169af6',
    messagingSenderId: '81377161795',
    projectId: 'saasaki-assignment',
    authDomain: 'saasaki-assignment.firebaseapp.com',
    storageBucket: 'saasaki-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDegiqILjuvanLhuloHCQ09tweRgo8S0x8',
    appId: '1:81377161795:android:2bcb0f2d6dd309db169af6',
    messagingSenderId: '81377161795',
    projectId: 'saasaki-assignment',
    storageBucket: 'saasaki-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-RzFgI65kZBd6IITBLPACeJwIH0mTuV4',
    appId: '1:81377161795:ios:d5d01e183e71ee95169af6',
    messagingSenderId: '81377161795',
    projectId: 'saasaki-assignment',
    storageBucket: 'saasaki-assignment.appspot.com',
    iosBundleId: 'com.example.saasakiAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-RzFgI65kZBd6IITBLPACeJwIH0mTuV4',
    appId: '1:81377161795:ios:d5d01e183e71ee95169af6',
    messagingSenderId: '81377161795',
    projectId: 'saasaki-assignment',
    storageBucket: 'saasaki-assignment.appspot.com',
    iosBundleId: 'com.example.saasakiAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtmRFSWTUM6tmVAegbDyv6u_zlwvmGM28',
    appId: '1:81377161795:web:773b23ced14a91c2169af6',
    messagingSenderId: '81377161795',
    projectId: 'saasaki-assignment',
    authDomain: 'saasaki-assignment.firebaseapp.com',
    storageBucket: 'saasaki-assignment.appspot.com',
  );
}
